import Header from "@/components/Shared/Header";
import "./globals.scss";
import { PT_Sans } from "next/font/google";
import { PT_Serif } from "next/font/google";
import Navbar from "@/components/Shared/Navbar";
import Footer from "@/components/Shared/Footer";

const sans = PT_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["400", "700"],
});

const serif = PT_Serif({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-serif",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={` ${serif.className} ${sans.className} `}>
        <Header />
        <Navbar />
        <main className="flex flex-col gap-[3.3rem] max-w-[100vw] overflow-hidden">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
